config/routes.rb
Rails.application.routes.draw do
  resources :donations
  resources :orders
  get 'cart/show'
  resources :shipping_infos
  resources :images
  resources :art_works, path: :art 
  # get 'pages/landing'
  get 'about' => 'pages#about'
  get 'how-it-works' => 'pages#how_it_works', as: :how_it_works
  get 'timeline' => 'pages#timeline', as: :timeline
  get 'dashboard' => 'pages#dashboard', as: :dashboard
  get 'mission' => 'pages#mission', as: :mission

  post 'donation_paid/:id' => 'pages#donation_paid', as: :donation_paid
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  
  root "pages#landing"
end

app/views/pages/about.html.erb
<div class=" container bg-white px-6 py-32 lg:px-8">
  <div class="mx-auto max-w-3xl text-base leading-7 text-gray-700">
    <p class="text-base font-semibold leading-7 text-indigo-600">The Story</p>
    <h1 class="mt-2 text-3xl font-bold tracking-tight text-gray-900 sm:text-4xl">Failing Forward</h1> 
    <p class="mt-6 text-xl leading-8">Hi, I'm Dillon. I'm the artist behind the pieces here, and the developer who built this website.</p>
    <div class="mt-10 max-w-2xl">
      <p>The story of this site starts when El Salvador made Bitcoin legal tender. I had just gotten a remote engineering job to be a
       digital nomad for a while. When El Salvador made the announcement, I canceled my airbnb's, changed my flight and moved there to 
       see what was going on. I learned some important things</p>
      <ul role="list" class="mt-8 max-w-xl space-y-8 text-gray-600">
        <li class="flex gap-x-3">
          <svg class="mt-1 h-5 w-5 flex-none text-indigo-600" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
            <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.857-9.809a.75.75 0 00-1.214-.882l-3.483 4.79-1.88-1.88a.75.75 0 10-1.06 1.061l2.5 2.5a.75.75 0 001.137-.089l4-5.5z" clip-rule="evenodd" />
          </svg>
          <span><strong class="font-semibold text-gray-900">Bitcoin Is Important For Humanity</strong> There's so many things wrong with out banking system. Things like inflation, digital tracking and the government deciding what you can spen your money on are a few examples.</span>
        </li>
        <li class="flex gap-x-3">
          <svg class="mt-1 h-5 w-5 flex-none text-indigo-600" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
            <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.857-9.809a.75.75 0 00-1.214-.882l-3.483 4.79-1.88-1.88a.75.75 0 10-1.06 1.061l2.5 2.5a.75.75 0 001.137-.089l4-5.5z" clip-rule="evenodd" />
          </svg>
          <span><strong class="font-semibold text-gray-900">Programable Money Is Awesome For Business</strong> Things like automatic profit sharing, dynamic investments, automatic supply purchasing based on triggers are some of the many applications that businesses and entrepreneurs have yet to innovate with. There is so much oportunity in the way of programmable money.</span>
        </li>
        <li class="flex gap-x-3">
          <svg class="mt-1 h-5 w-5 flex-none text-indigo-600" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
            <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.857-9.809a.75.75 0 00-1.214-.882l-3.483 4.79-1.88-1.88a.75.75 0 10-1.06 1.061l2.5 2.5a.75.75 0 001.137-.089l4-5.5z" clip-rule="evenodd" />
          </svg>
          <span><strong class="font-semibold text-gray-900">It's only digital money.</strong>It's really hard buy things in the real world with it. 
          Many of the vendors in El Salvador complained about this. If they accepted Bitcoin, they would need to sell it for cash at an ATM for a 5% fee, and that's assuming it doesn't go down. 
          A 5% fee in a 3rd world country is a lot.</span>
        </li>
      </ul>
      <p class="mt-8">So these are some interesting things. And I'm not just curious, I like to build and invent things</p>
      <h2 class="mt-16 text-2xl font-bold tracking-tight text-gray-900">So I decided to sell coffee</h2>
      <p class="mt-6">While I was pretending to work at my remote job, I was hustling in the coffee business. Mostly as a proof of concept. Trying to see what the business model would look like for a crypto for CPG company would look like. </p>
      <figure class="mt-10 border-l border-indigo-600 pl-9">
        <blockquote class="font-semibold text-gray-900">
          <p>Because how will crypto make us free when you have to stay glued to a screen?</p>
        </blockquote>
      </figure>
      <p class="mt-10">The real world is where it matters. But, the time I chose to do this was the worst time possible. Shipping rates were insane, thanks to covid. Recurring payments were impossible, and I lost my job. </P>
      <p class="mt-10">My manager got wise to what I was doing, and my performance was slacking. I was fired. I ran out of money and couldn't pay for any business expense. I moved to Austin Tx to persue this coffee business. But lost my 
      income around 5 months after I moved there.
    
      </p>
    </div>
    

 <%
=begin%>
 <figure class="mt-16">
      <img class="aspect-video rounded-xl bg-gray-50 object-cover" src="https://images.unsplash.com/photo-1500648767791-00dcc994a43e?ixlib=rb-1.2.1&auto=format&fit=facearea&w=1310&h=873&q=80&facepad=3" alt="">
      <figcaption class="mt-4 flex gap-x-2 text-sm leading-6 text-gray-500">
        <svg class="mt-0.5 h-5 w-5 flex-none text-gray-300" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
          <path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a.75.75 0 000 1.5h.253a.25.25 0 01.244.304l-.459 2.066A1.75 1.75 0 0010.747 15H11a.75.75 0 000-1.5h-.253a.25.25 0 01-.244-.304l.459-2.066A1.75 1.75 0 009.253 9H9z" clip-rule="evenodd" />
        </svg>
        Faucibus commodo massa rhoncus, volutpat.
      </figcaption>
    </figure>  
<%
=end%>

    <div class="mt-16 max-w-2xl">
      <h2 class="text-2xl font-bold tracking-tight text-gray-900">The last 2 years have been a struggle.</h2>
      <p class="mt-6">Not really caring about any company I got a job at, I havent lasted long ant any of them. For the last 2 years I held 3 jobs. One for 7 months. 
      Another for 6, and the last one was a contract that only lasted a month. Not from bad performance, but from taking too long to do things.</p>
      <p class="mt-8">It's been a real challenge, putting in hours toward someone else's "get rich" plan when all you want to do is work on something that feels 
      important for the future of humanity.</p>
      <p class="mt-8">When your motivations lie in making sure your great grand children, who you'll never meet, live in a world that is good. 
      Everything else is difficult to work on.</p>
    </div>
    <div class="mt-16 max-w-2xl">
      <h2 class="text-2xl font-bold tracking-tight text-gray-900">You're probably thinking I'm irresponsible</h2>
      <p class="mt-6">Its taken being responsible to work for people. But my girlfriend actually convinced me that I need to stop hiding my talents from the world. I promised her that I would. So here I am. Comitted to keeping my promise and making something that might be useful to humanity.</p>
       <figure class="mt-10 border-l border-indigo-600 pl-9">
        <blockquote class="font-semibold text-gray-900">
          <p> So no more time and energy is wasted helping someone else fulfill their dreams.</p>
        </blockquote>
      </figure>
      
    </div>
    <div class="mt-16 max-w-2xl">
      <h2 class="text-2xl font-bold tracking-tight text-gray-900">So I decided to say "Fuck It."</h2>
      <p class="mt-6">I'm an artist. The energy that I've spent working the 9 to 5 has been a soul suicide. I've been sitting on this art ever 
      since I lived in El Salvador. I barley knew the language and didn't know anyone when I moved there so I spent my alone time at night making 
      these pieces. Each one has it's own story you can see in their descriptions.</p>
      <p class="mt-6">This is my full time job now</p>
      <p class="mt-6">Selling art.</p>
    </div>
    <div class="mt-16 max-w-2xl">
      <h2 class="text-2xl font-bold tracking-tight text-gray-900">And I still want to help humanity.</h2>
      <p class="mt-6">So that's why I'm selling these NFT's. You're not buying the NFT, your buying the physical art. the NFT just gives you some unique features. <%= link_to "How it works", how_it_works_path, class: "font-semibold text-indigo-600 hover:text-indigo-500" %> </p>
      <p class="mt-6">This seems like a good way to bring crypto into the physical world. There are a lot of things possible but I'm starting off small. As a humble artist and a failed developer. Maybe this can be useful to the world</p>
    </div>
    <div class="mt-16 max-w-2xl">
      <h2 class="text-2xl font-bold tracking-tight text-gray-900">This won't be just for me.</h2>
      <p class="mt-6">Right now I'm the only one selling art here. I'm doing that on purpose. This is a new realm for everyone. There are many unknowns.</p>
      <p class="mt-6">Once I've sold enough of this collection, and tested the protocol in the real world, this website will be open for anyone to add their art. This will help artists and buyers of fine art, and ensure quality NFT's are made. Not randomly generated JPEGS. </p>
      <p class="mt-6"><%= link_to "See The Roadmap", timeline_path, class: "font-semibold text-indigo-600 hover:text-indigo-500" %>  </p>
    </div>
    <figure class="mt-10 border-l border-indigo-600 pl-9">
        <blockquote class="font-semibold text-gray-900">
          <p> This might make me bankrupt. But feels worth it.</p>
        </blockquote>
      </figure>
  </div>
</div>

app/views/pages/dashboard.html.erb
  <div class="relative isolate overflow-hidden pt-16">
    <!-- Secondary navigation -->
    <header class="pb-4 pt-6 sm:pb-6">
      <div class="mx-auto max-w-7xl px-4 py-10 sm:px-6 lg:px-8">
  <!-- We've used 3xl here, but feel free to try other max-widths based on your needs -->
  <div class="mx-auto max-w-3xl">
      <div class="mt-10 py-10 container mx-auto"> 
      <%= form_for @new_donation do |f| %>
        <label for="donation" class="block text-3xl font-medium leading-6 text-gray-900">Donate Sats</label>
        <div class="mt-2">
        <%= f.number_field :amount_in_sats, class: "block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6"  %>
        </div>
        <p class="mt-2 text-sm text-gray-500 mb-4" id="email-description">Only if you believe in making Bitcoin the global standard for currency.</p>
        <%= f.submit "Generate Invoice", class: "inline-flex items-center gap-x-2 rounded-md bg-indigo-600 px-3.5 py-2.5 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600" %>
      <% end %>
      </div>
  </div>
</div>

    </header>

    <!-- Stats -->
    <div class="border-b border-b-gray-900/10 lg:border-t lg:border-t-gray-900/5">
      <dl class="mx-auto grid max-w-7xl grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 lg:px-2 xl:px-0">
        <div class="flex items-baseline flex-wrap justify-between gap-y-2 gap-x-4 border-t border-gray-900/5 px-4 py-10 sm:px-6 lg:border-t-0 xl:px-8">
          <dt class="text-sm font-medium leading-6 text-gray-500">Total Donated</dt>
          <dd class="w-full flex-none text-3xl font-medium leading-10 tracking-tight text-gray-900"><%= @donations_total %> SATS</dd>
        </div>
        <div class="flex items-baseline flex-wrap justify-between gap-y-2 gap-x-4 border-t border-gray-900/5 px-4 py-10 sm:px-6 lg:border-t-0 xl:px-8 sm:border-l">
          <dt class="text-sm font-medium leading-6 text-gray-500">Total Donations</dt>
          <dd class="w-full flex-none text-3xl font-medium leading-10 tracking-tight text-gray-900"><%= @donation_count %></dd>
        </div>
        <div class="flex items-baseline flex-wrap justify-between gap-y-2 gap-x-4 border-t border-gray-900/5 px-4 py-10 sm:px-6 lg:border-t-0 xl:px-8 lg:border-l">
          <dt class="text-sm font-medium leading-6 text-gray-500">Highest Donation</dt>
          <dd class="w-full flex-none text-3xl font-medium leading-10 tracking-tight text-gray-900"><%=@highest_donation%> Sats</dd>
        </div>
        <div class="flex items-baseline flex-wrap justify-between gap-y-2 gap-x-4 border-t border-gray-900/5 px-4 py-10 sm:px-6 lg:border-t-0 xl:px-8 sm:border-l">
          <dt class="text-sm font-medium leading-6 text-gray-500">Your Contribution</dt>
          <dd class="w-full flex-none text-3xl font-medium leading-10 tracking-tight text-gray-900"><%=@user_contributions %></dd>
        </div>
      </dl>
    </div>

    <div class="absolute left-0 top-full -z-10 mt-96 origin-top-left translate-y-40 -rotate-90 transform-gpu opacity-20 blur-3xl sm:left-1/2 sm:-ml-96 sm:-mt-10 sm:translate-y-0 sm:rotate-0 sm:transform-gpu sm:opacity-50" aria-hidden="true">
      <div class="aspect-[1154/678] w-[72.125rem] bg-gradient-to-br from-[#FF80B5] to-[#9089FC]" style="clip-path: polygon(100% 38.5%, 82.6% 100%, 60.2% 37.7%, 52.4% 32.1%, 47.5% 41.8%, 45.2% 65.6%, 27.5% 23.4%, 0.1% 35.3%, 17.9% 0%, 27.7% 23.4%, 76.2% 2.5%, 74.2% 56%, 100% 38.5%)"></div>
    </div>
  </div>

  <div class="space-y-16 py-16 xl:space-y-20">
    <!-- Recent activity table -->
    <div>
      <div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
        <h2 class="mx-auto max-w-2xl text-base font-semibold leading-6 text-gray-900 lg:mx-0 lg:max-w-none">Activity</h2>
      </div>
      <div class="mt-6 overflow-hidden border-t border-gray-100">
        <div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
          <div class="mx-auto max-w-2xl lg:mx-0 lg:max-w-none">
            <table class="w-full text-left">
              <thead class="sr-only">
                <tr>
                  <th>Amount</th>
                  <th class="hidden sm:table-cell">Client</th>
                  <th>More details</th>
                </tr>
              </thead>
              <tbody>
                <tr class="text-sm leading-6 text-gray-900">
                  <th scope="colgroup" colspan="3" class="relative isolate py-2 font-semibold">
                    <div class="absolute inset-y-0 right-full -z-10 w-screen border-b border-gray-200 bg-gray-50"></div>
                    <div class="absolute inset-y-0 left-0 -z-10 w-screen border-b border-gray-200 bg-gray-50"></div>
                  </th>
                </tr>
                <% @donations.each do |donation| %>
                    <tr>
                    <td class="relative py-5 pr-6">
                        <div class="flex gap-x-6">
                        <svg class="hidden h-6 w-5 flex-none text-gray-400 sm:block" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                            <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm-.75-4.75a.75.75 0 001.5 0V8.66l1.95 2.1a.75.75 0 101.1-1.02l-3.25-3.5a.75.75 0 00-1.1 0L6.2 9.74a.75.75 0 101.1 1.02l1.95-2.1v4.59z" clip-rule="evenodd" />
                        </svg>
                        <div class="flex-auto">
                            <div class="flex items-start gap-x-3">
                            <div class="text-sm font-medium leading-6 text-gray-900"><%= donation.amount_in_sats%> sats</div>
                            <div class="rounded-md py-1 px-2 text-xs font-medium ring-1 ring-inset text-green-700 bg-green-50 ring-green-600/20"><%= donation.status.titleize %></div>
                            </div>
                        </div>
                        </div>
                        <div class="absolute bottom-0 right-full h-px w-screen bg-gray-100"></div>
                        <div class="absolute bottom-0 left-0 h-px w-screen bg-gray-100"></div>
                    </td>
                    <td class="hidden py-5 pr-6 sm:table-cell">
                        <div class="text-sm leading-6 text-gray-900">Reform</div>
                        <div class="mt-1 text-xs leading-5 text-gray-500">Website redesign</div>
                    </td>
                    <td class="py-5 text-right">
                        <div class="flex justify-end">
                        <a href="" class="text-sm font-medium leading-6 text-indigo-600 hover:text-indigo-500">Match Donation<span class="hidden sm:inline"> transaction</span><span class="sr-only">, invoice #00012, Reform</span></a>
                        </div>
                        <div class="mt-1 text-xs leading-5 text-gray-500">Invoice <span class="text-gray-900">#000<%= donation.id %></span></div>
                    </td>
                    </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>

  </div>

app/views/pages/how_it_works.html.erb
<div class="bg-white">
  <div class="mx-auto max-w-2xl px-4 py-24 sm:px-6 sm:py-32 lg:max-w-7xl lg:px-8">
    <div class="mx-auto max-w-3xl text-center">
      <p class="mt-4 text-gray-500">This site is still a work in progress. <%= link_to "Donate here", new_donation_path %></p>
      <h2 class="text-3xl font-bold tracking-tight text-gray-900 sm:text-4xl">How It Works</h2>
      <p class="mt-4 text-gray-500">NFT's on Bitcoin for physical art is a new concept. But it's really cool. This is how it works</p>
    </div>

    <div class="mt-16 space-y-16">
      <div class="flex flex-col-reverse lg:grid lg:grid-cols-12 lg:items-center lg:gap-x-8">
        <div class="mt-6 lg:col-span-5 lg:row-start-1 lg:mt-0 xl:col-span-4 lg:col-start-1">
          <h3 class="text-lg font-medium text-gray-900">Find a piece you like</h3>
          <p class="mt-2 text-sm text-gray-500">Right now there are 8 pieces available. I made each of these by hand on my ipad. No AI was used. There are 3 sizes available and only 33 of each size. These are the first of their kind and tell a better story than any art you'll have on your walls</p>
        </div>
        <div class="flex-auto lg:col-span-7 lg:row-start-1 xl:col-span-8 lg:col-start-6 xl:col-start-5">
          <div class="aspect-h-2 aspect-w-5 overflow-hidden rounded-lg bg-gray-100">
            <img src="https://tailwindui.com/img/ecommerce-images/product-feature-07-detail-01.jpg" alt="White canvas laptop sleeve with gray felt interior, silver zipper, and tan leather zipper pull." class="object-cover object-center">
          </div>
        </div>
      </div>
      <div class="flex flex-col-reverse lg:grid lg:grid-cols-12 lg:items-center lg:gap-x-8">
        <div class="mt-6 lg:col-span-5 lg:row-start-1 lg:mt-0 xl:col-span-4 lg:col-start-8 xl:col-start-9">
          <h3 class="text-lg font-medium text-gray-900">Order then pay</h3>
          <p class="mt-2 text-sm text-gray-500">Once you order you'll be directed to a place to add your shipping address. Don't worry, this isn't saved on the ordinal, it's kept private. I just need to know where to send your art!</p>
          <p class="mt-2 text-sm text-gray-500">Then you'll be shown a lightning invoice. Once this is paid you'll recieve your Ordinal in your wallet and the backend will create an order for the print of whatever artwork you chose.</p>
        </div>
        <div class="flex-auto lg:col-span-7 lg:row-start-1 xl:col-span-8 lg:col-start-1">
          <div class="aspect-h-2 aspect-w-5 overflow-hidden rounded-lg bg-gray-100">
            <img src="https://tailwindui.com/img/ecommerce-images/product-feature-07-detail-02.jpg" alt="Detail of zipper pull with tan leather and silver rivet." class="object-cover object-center">
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="mx-auto max-w-2xl px-4 pb-24 sm:px-6  lg:max-w-7xl lg:px-8">
    <div class="max-w-3xl">
      <h2 id="features-heading" class="font-medium text-gray-500"></h2>
      <p class="mt-2 text-3xl font-bold tracking-tight text-gray-900 sm:text-4xl">About The Art</p>
      <p class="mt-4 text-gray-500">I really wanted to sell high quality art. So I haven't cut any corners in getting this process set up.</p>
      <p class="mt-4 text-gray-500">I am using Pictorem to fulfil orders. 
                                    When an NFT is purchased, the backend of this website 
                                    automatically calls their API and creates an order for high quality canvass prints</P>
      <p class="mt-4 text-gray-500">Each piece comes with the contract of the 
                                    NFT in the package. As well as a way to transfer 
                                    the NFT to a new wallet in case your wallet gets hacked, or you lose your keys.</P>
    </div>

    <div class="mt-7 grid grid-cols-1 items-start gap-x-6 gap-y-16 sm:mt-16 sm:grid-cols-2 lg:grid-cols-4 lg:gap-x-8">
      <div class="flex flex-col-reverse">
        <div class="mt-6">
          <h3 class="text-sm font-medium text-gray-900">Gallery Level Prints</h3>
          <p class="mt-2 text-sm text-gray-500">Each canvas is designed to meet art galleries' and museum's longevity requirements. This means that consistency of shades will last for up to 200 years. </p>
        </div>
        <div class="aspect-h-1 aspect-w-1 overflow-hidden rounded-lg bg-gray-100">
          <img src="https://tailwindui.com/img/ecommerce-images/product-feature-08-detail-01.jpg" alt="Green cardstock box containing white, beige, and brown cards." class="object-cover object-center">
        </div>
      </div>
      <div class="flex flex-col-reverse">
        <div class="mt-6">
          <h3 class="text-sm font-medium text-gray-900">Ready To Hang Wire</h3>
          <p class="mt-2 text-sm text-gray-500">From out of the box, to hanging on your wall. Each canvass comes with a ready to hang wire installed.</p>
        </div>
        <div class="aspect-h-1 aspect-w-1 overflow-hidden rounded-lg bg-gray-100">
          <img src="https://tailwindui.com/img/ecommerce-images/product-feature-08-detail-02.jpg" alt="Green cardstock box open with 50 cards inside." class="object-cover object-center">
        </div>
      </div>
      <div class="flex flex-col-reverse">
        <div class="mt-6">
          <h3 class="text-sm font-medium text-gray-900">Mounted Frame</h3>
          <p class="mt-2 text-sm text-gray-500">Each canvass is set inside a floating frame. This makes it feel and look complete and is a night and day difference to just a canvass on the wall with no frame.</p>
        </div>
        <div class="aspect-h-1 aspect-w-1 overflow-hidden rounded-lg bg-gray-100">
          <img src="https://tailwindui.com/img/ecommerce-images/product-feature-08-detail-03.jpg" alt="Detail of white today card, beige next card, and brown someday card with dot grid." class="object-cover object-center">
        </div>
      </div>
      <div class="flex flex-col-reverse">
        <div class="mt-6">
          <h3 class="text-sm font-medium text-gray-900">Guarenteed Quality</h3>
          <p class="mt-2 text-sm text-gray-500">The main reason I am using Pictorem. Each piece has a dedicated quality check and review to make sure each piece is of the highest quality. They also accept bitcoin, which helps make the backend automatic.</p>
        </div>
        <div class="aspect-h-1 aspect-w-1 overflow-hidden rounded-lg bg-gray-100">
          <img src="https://tailwindui.com/img/ecommerce-images/product-feature-08-detail-04.jpg" alt="Stack of three green cardstock boxes with 3 hole cutouts showing cards inside." class="object-cover object-center">
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/mission.html.erb
<div class="bg-gray-900">


  <main class="relative isolate mt-12">
    <!-- Background -->
    <div class="absolute inset-x-0 top-4 -z-10 h-full flex transform-gpu justify-center overflow-hidden blur-3xl" aria-hidden="true">
      <div class="aspect-[1108/632] w-[69.25rem] flex-none bg-gradient-to-r from-[#80caff] to-[#4f46e5] opacity-25" style="clip-path: polygon(73.6% 51.7%, 91.7% 11.8%, 100% 46.4%, 97.4% 82.2%, 92.5% 84.9%, 75.7% 64%, 55.3% 47.5%, 46.5% 49.4%, 45% 62.9%, 50.3% 87.2%, 21.3% 64.1%, 0.1% 100%, 5.4% 51.1%, 21.4% 63.9%, 58.9% 0.2%, 73.6% 51.7%)"></div>
    </div>

    <!-- Header section -->
    <div class="px-6 pt-14 lg:px-8">
      <div class="mx-auto max-w-2xl pt-24 text-center sm:pt-40">
        <h2 class="text-4xl font-bold tracking-tight text-white sm:text-6xl">Make Bitcoin The Global Standard</h2>
        <p class="mt-6 text-lg leading-8 text-gray-300">I have tried a lot of different approaches to achieve this. From living in El Salvador to selling coffee, I've learned one thing. For mass adoption and the financial freedom of humanity, Bitcoin needs to cross the digital barrier into the physical world. That's why I'm selling art, with Ordinals (Bitcoin NFTs) attached as proof of ownership and the certificate of authenticity.</p>
        <p class="mt-10 text-lg leading-8 text-gray-300">I don't know where this is going to go. This is largely an expirement. Once Things have been figured out from me selling my art, this website will hopefully turn into an awesome combination of Etsy and Opensea, but not for shitcoins, for Bitcoin.</p>
        <p class="mt-10 text-lg leading-8 text-gray-300">Setting up a good world for the generations of people that we'll never meet is my driving motivator. Only because that's what I wish our past generations did for us.</p>
        <%= link_to "Donate", dashboard_path, class: "mt-12 text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-4 py-2 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800" %>  
      </div>
    </div>  
    <div class="px-6 pt-14 lg:px-8">
      <div class="mx-auto max-w-2xl pt-24 text-center sm:pt-40">
        </div>
    </div>
  </main>
</div>