config/routes.rb
Rails.application.routes.draw do
  resources :donations
  resources :orders
  get 'cart/show'
  resources :shipping_infos
  resources :images
  resources :art_works, path: :art 
  # get 'pages/landing'
  get 'about' => 'pages#about'
  get 'how-it-works' => 'pages#how_it_works', as: :how_it_works
  get 'timeline' => 'pages#timeline', as: :timeline
  get 'dashboard' => 'pages#dashboard', as: :dashboard
  get 'mission' => 'pages#mission', as: :mission

  post 'donation_paid/:id' => 'pages#donation_paid', as: :donation_paid
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  
  root "pages#landing"
end

app/models/art_work.rb
class ArtWork < ApplicationRecord
  include Rails.application.routes.url_helpers

  belongs_to :user
  has_many :variants

  has_one_attached :main_image

  def create_variants
    # create a variant for each size

    # 20x15, 30x22, 42x31
    #   0,     1,     2
    
    [0, 1, 2].each do |size|
      # create a variant with the size
      variant = Variant.create(
        art_work: self,
        size: size,
        width: size == 0 ? 20 : size == 1 ? 30 : 42,
        height: size == 0 ? 15 : size == 1 ? 22 : 31,
      )

    end
  end

  def main_image_url
    rails_blob_url(self.main_image, host: 'localhost:3000')
  end
end

app/controllers/art_works_controller.rb
class ArtWorksController < ApplicationController
    before_action :authenticate_user!, only: [:new, :create]
    def index
        @current_user = current_user
        @user_is_admin = @current_user && @current_user&.admin?
        @art_works = ArtWork.all
    end

    def show
        @art_work = ArtWork.find(params[:id])
    end

    def new
        @art_work = ArtWork.new
    end

    def add_variants
        @art_work = ArtWork.find(params[:id])
        @variant = @art_work.variants.build
    end
    
    def create_variants
        @art_work = ArtWork.find(params[:id])
        @variant = @art_work.variants.build(variant_params)
        if @variant.save
            redirect_to @art_work
        else
            render 'add_variants'
        end
    end    

    def create
        @art_work = ArtWork.new(art_work_params)
        @art_work.user = current_user
        if @art_work.save
            redirect_to @art_work
        else
            render 'new'
        end
    end

    private

    def art_work_params
        params.require(:art_work).permit(:title, :description, :contract_address, :medium_type, :main_image, variant: [:size, :width, :height, :price_in_eth, :price_in_usd])
    end
end

app/helpers/art_works_helper.rb
module ArtWorksHelper
end

app/views/art_works/index.html.erb
<div class="bg-white">
  <div class="mx-auto max-w-2xl px-4 py-16 sm:px-6 sm:py-24 lg:max-w-7xl lg:px-8">
    <h2 class="text-xl font-bold text-gray-900">Art Work</h2>
    <% if @user_is_admin %>
      <%= link_to "Add Art Piece", new_art_work_path %>
    <% end %>
    <div class="mt-8 grid grid-cols-1 gap-y-12 sm:grid-cols-2 sm:gap-x-6 lg:grid-cols-4 xl:gap-x-8">
    <% @art_works.each do |art| %>
      <div>
        <%= link_to art_work_path(art) do %>
        <div class="relative">
          <div class="relative h-72 w-full overflow-hidden rounded-lg">
             <%= image_tag art.main_image, class: "h-full w-full object-contain"%>
          </div>
          <div class="relative mt-4">
            <h3 class="text-sm font-medium text-gray-900"><%= art.title%></h3>
            <p class="mt-1 text-sm text-gray-500">3 Sizes Available</p>
          </div>
          <div class="absolute inset-x-0 top-0 flex h-72 items-end justify-end overflow-hidden rounded-lg p-4">
            <div aria-hidden="true" class="absolute inset-x-0 bottom-0 h-36 bg-gradient-to-t from-black opacity-50"></div>
            <p class="relative text-lg font-semibold text-white">From 0.007 BTC</p>
          </div>
        </div>
        <div class="mt-6">
          <%
=begin%>
 <a href="#" class="relative flex items-center justify-center rounded-md border border-transparent bg-gray-100 px-8 py-2 text-sm font-medium text-gray-900 hover:bg-gray-200">Add To Cart<span class="sr-only">, Zip Tote Basket</span></a> 
<%
=end%>
        </div>
        <% end %>
      </div>

      <!-- More products... -->
    <% end %>
    </div>
  </div>
</div>

app/views/art_works/new.html.erb
<div class="container mx-auto">
<%= form_for @art_work do |f| %>
  <div class="space-y-12">
        <h2 class="text-base font-semibold leading-7 text-gray-900">Create A New Piece</h2>
        <%
=begin%>
 <p class="mt-1 text-sm leading-6 text-gray-600">This will not create the smart contract.</p> 
<%
=end%>
    <div class="grid grid-cols-1 gap-x-8 gap-y-10 border-b border-gray-900/10 pb-12 md:grid-cols-3">
      <div>
      </div>
        <div class="col-span-full">
            <label for="cover-photo" class="block text-sm font-medium leading-6 text-gray-900">photo</label>
            <div class="mt-2 flex justify-center rounded-lg border border-dashed border-gray-900/25 px-6 py-10">
                <div class="text-center">
                    <svg class="mx-auto h-12 w-12 text-gray-300" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true">
                    <path fill-rule="evenodd" d="M1.5 6a2.25 2.25 0 012.25-2.25h16.5A2.25 2.25 0 0122.5 6v12a2.25 2.25 0 01-2.25 2.25H3.75A2.25 2.25 0 011.5 18V6zM3 16.06V18c0 .414.336.75.75.75h16.5A.75.75 0 0021 18v-1.94l-2.69-2.689a1.5 1.5 0 00-2.12 0l-.88.879.97.97a.75.75 0 11-1.06 1.06l-5.16-5.159a1.5 1.5 0 00-2.12 0L3 16.061zm10.125-7.81a1.125 1.125 0 112.25 0 1.125 1.125 0 01-2.25 0z" clip-rule="evenodd" />
                    </svg>
                    <div class="mt-4 flex text-sm leading-6 text-gray-600">
                    <label for="file-upload" class="relative cursor-pointer rounded-md bg-white font-semibold text-indigo-600 focus-within:outline-none focus-within:ring-2 focus-within:ring-indigo-600 focus-within:ring-offset-2 hover:text-indigo-500">
                        <span>Upload a file</span>
                    </label>
                        <%= f.file_field :main_image %>
                        
                    </div>
                    <p class="text-xs leading-5 text-gray-600">PNG, JPG, GIF up to 10MB</p>
                </div>
            </div>
        </div>

      <div class="grid max-w-2xl grid-cols-1 gap-x-6 gap-y-8 sm:grid-cols-6 md:col-span-2">
        <div class="sm:col-span-4">
          <label for="website" class="block text-sm font-medium leading-6 text-gray-900">Name</label>
          <div class="mt-2">
            <div class="flex rounded-md shadow-sm ring-1 ring-inset ring-gray-300 focus-within:ring-2 focus-within:ring-inset focus-within:ring-indigo-600 sm:max-w-md">
              <%= f.text_field :title, class: "block flex-1 border-0 bg-transparent py-1.5 pl-1 text-gray-900 placeholder:text-gray-400 focus:ring-0 sm:text-sm sm:leading-6", placeholder: "" %>
            </div>
          </div>
        </div>

        <div class="col-span-full">
          <label for="about" class="block text-sm font-medium leading-6 text-gray-900">Description</label>
          <div class="mt-2">
            <%= f.text_area :description, rows: "4", class: "block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6"%>
          </div>
          <p class="mt-3 text-sm leading-6 text-gray-600">Write a few sentences about your art.</p>
        </div>


      </div>
    </div>

  <div class="mt-6 flex items-center justify-end gap-x-6">
    <%= f.submit "Create", class: "rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600" %>
  </div>
<%end%>
</div>

app/views/art_works/show.html.erb
<div class="bg-gray-50">
    <!-- Product -->
    <div class="bg-white">
      <div class="mx-auto max-w-2xl px-4 pb-24 pt-16 sm:px-6 sm:pb-32 sm:pt-24 lg:grid lg:max-w-7xl lg:grid-cols-2 lg:gap-x-8 lg:px-8">
        <!-- Product details -->
        <div class="lg:max-w-lg lg:self-end">

          <div class="mt-4">
            <h1 class="text-3xl font-bold tracking-tight text-gray-900 sm:text-4xl"><%= @art_work.title %></h1>
          </div>

          <section aria-labelledby="information-heading" class="mt-4">
            <h2 id="information-heading" class="sr-only">Product information</h2>

        
            <div class="mt-4 space-y-6">
              <p class="text-base text-gray-500"><%= @art_work.description %></div>
            <div class="mt-6 flex items-center">
              <svg class="h-5 w-5 flex-shrink-0 text-green-500" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                <path fill-rule="evenodd" d="M16.704 4.153a.75.75 0 01.143 1.052l-8 10.5a.75.75 0 01-1.127.075l-4.5-4.5a.75.75 0 011.06-1.06l3.894 3.893 7.48-9.817a.75.75 0 011.05-.143z" clip-rule="evenodd" />
              </svg>
              <p class="ml-2 text-sm text-gray-500">In stock and ready to ship</p>
            </div>
          </section>
        </div>

        <!-- Product image -->
        <div class="mt-10 lg:col-start-2 lg:row-span-2 lg:mt-0 lg:self-center">
          <div class="aspect-h-1 aspect-w-1 overflow-hidden rounded-lg">
            
            <%= image_tag @art_work.main_image, class: 'object-scale-down' %>
          </div>
          
        </div>

        <!-- Product form -->
        <div class="mt-10 lg:col-start-1 lg:row-start-2 lg:max-w-lg lg:self-start">
          <section aria-labelledby="options-heading">
            <h2 id="options-heading" class="sr-only">Product options</h2>

            <%
=begin%>
 <form> 
<%
=end%>
              <div class="sm:flex sm:justify-between">
                <!-- Size selector -->
                <fieldset>
                  <legend class="block text-sm font-medium text-gray-700">Select Your Size</legend>
                  <div class="mt-1 grid grid-cols-4 gap-4 " data-controller="order">
                    <!-- Active: "ring-2 ring-indigo-500" -->
                    <div  class="relative block cursor-pointer rounded-lg border border-gray-300 p-4 focus:outline-none" data-action="click->order#selectSmall" data-order-target="size">
                      <input type="radio" name="size-choice" value="18L" class="sr-only" aria-labelledby="size-choice-0-label" aria-describedby="size-choice-0-description">
                      <p id="size-choice-0-label" class="text-base font-medium text-gray-900">Small</p>
                      <p id="size-choice-0-description" class="mt-1 text-sm text-gray-500">20" x 15"</p>
                      <!--
                        Active: "border", Not Active: "border-2"
                        Checked: "border-indigo-500", Not Checked: "border-transparent"
                      -->
                      <div class="pointer-events-none absolute -inset-px rounded-lg border-2" aria-hidden="true"></div>
                    </div>
                    <!-- Active: "ring-2 ring-indigo-500" -->
                    <div class="relative block cursor-pointer rounded-lg border border-gray-300 p-4 focus:outline-none" data-action="click->order#selectMedium" data-order-target="size">
                      <input type="radio" name="size-choice" value="20L" class="sr-only" aria-labelledby="size-choice-1-label" aria-describedby="size-choice-1-description">
                      <p id="size-choice-1-label" class="text-base font-medium text-gray-900">Medium</p>
                      <p id="size-choice-1-description" class="mt-1 text-sm text-gray-500">30" x 22"</p>
                      <!--
                        Active: "border", Not Active: "border-2"
                        Checked: "border-indigo-500", Not Checked: "border-transparent"
                      -->
                      <div class="pointer-events-none absolute -inset-px rounded-lg border-2" aria-hidden="true"></div>
                    </div>
                    <div class="relative block cursor-pointer rounded-lg border border-gray-300 p-4 focus:outline-none" data-action="click->order#selectLarge" data-order-target="size">
                      <input type="radio" name="size-choice" value="20L" class="sr-only" aria-labelledby="size-choice-1-label" aria-describedby="size-choice-1-description">
                      <p id="size-choice-1-label" class="text-base font-medium text-gray-900">Large</p>
                      <p id="size-choice-1-description" class="mt-1 text-sm text-gray-500">42" x 31"</p>
                      <!--
                        Active: "border", Not Active: "border-2"
                        Checked: "border-indigo-500", Not Checked: "border-transparent"
                      -->
                      <div class="pointer-events-none absolute -inset-px rounded-lg border-2" aria-hidden="true"></div>
                    </div>
                    <div class="relative block rounded-lg pt-6 p-4 focus:outline-none">
                      <p id="size-choice-1-label" class="text-sm text-gray-500">Price</p>
                      <p id="size-choice-1-description" class="mt-1 text-base font-medium text-gray-900" data-order-target="price"></p>
                    </div>
                  </div>
                </fieldset>
                <div>
                  <h1></h1>
                </div>
              </div>

              <div class="mt-10">
                <div data-controller="modal">
                  <dialog data-modal-target="dialog" class="p-8 rounded-lg backdrop:bg-black/80">
                    <%= render 'layouts/forms/shipping_address_form' %>
                   

                  </dialog>

                
                  <button 
                          data-action="modal#open" 
                          class="flex w-full items-center justify-center rounded-md 
                                border border-transparent bg-indigo-600 px-8 py-3 
                                text-base font-medium text-white hover:bg-indigo-700 
                                focus:outline-none focus:ring-2 focus:ring-indigo-500 
                                focus:ring-offset-2 focus:ring-offset-gray-50">
                    Order
                  </button>
                </div>
              </div>
              <div class="mt-6 text-center">
                <a href="#" class="group inline-flex text-base font-medium">
                  <svg class="mr-2 h-6 w-6 flex-shrink-0 text-gray-400 group-hover:text-gray-500" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M9 12.75L11.25 15 15 9.75m-3-7.036A11.959 11.959 0 013.598 6 11.99 11.99 0 003 9.749c0 5.592 3.824 10.29 9 11.623 5.176-1.332 9-6.03 9-11.622 0-1.31-.21-2.571-.598-3.751h-.152c-3.196 0-6.1-1.248-8.25-3.285z" />
                  </svg>
                  <span class="text-gray-500 hover:text-gray-700">Lifetime Guarantee</span>
                  
                </a>
              </div>
            
          </section>
        </div>
      </div>
    </div>


    <div class="mx-auto max-w-2xl px-4 py-24 sm:px-6 sm:py-32 lg:max-w-7xl lg:px-8">
      <!-- Details section -->
      <section aria-labelledby="details-heading">
        <div class="flex flex-col items-center text-center">
          <h2 id="details-heading" class="text-3xl font-bold tracking-tight text-gray-900 sm:text-4xl">The Fine Details</h2>
          <p class="mt-3 max-w-3xl text-lg text-gray-600">All the art is printed with the highest quality Glicee printers, inspected for quality then carefully packaged so it's not damaged during shipping.</p>
        </div>

        <div class="mt-16 grid grid-cols-1 gap-y-16 lg:grid-cols-2 lg:gap-x-8">
          <div>
            <div class="aspect-h-2 aspect-w-3 w-full overflow-hidden rounded-lg">
              <img src="https://tailwindui.com/img/ecommerce-images/product-page-04-detail-product-shot-01.jpg" alt="Drawstring top with elastic loop closure and textured interior padding." class="h-full w-full object-cover object-center">
            </div>
            <p class="mt-8 text-base text-gray-500">The 20L model has enough space for 370 candy bars, 6 cylinders of chips, 1,220 standard gumballs, or any combination of on-the-go treats that your heart desires. Yes, we did the math.</p>
          </div>
          <div>
            <div class="aspect-h-2 aspect-w-3 w-full overflow-hidden rounded-lg">
              <img src="https://tailwindui.com/img/ecommerce-images/product-page-04-detail-product-shot-02.jpg" alt="Front zipper pouch with included key ring." class="h-full w-full object-cover object-center">
            </div>
            <p class="mt-8 text-base text-gray-500">Up your snack organization game with multiple compartment options. The quick-access stash pouch is ready for even the most unexpected snack attacks and sharing needs.</p>
          </div>
        </div>
      </section>

      <!-- Policies section -->
      <section aria-labelledby="policy-heading" class="mt-16 lg:mt-24">
        <h2 id="policy-heading" class="sr-only">Our policies</h2>
        <div class="grid grid-cols-1 gap-y-12 sm:grid-cols-2 sm:gap-x-6 lg:grid-cols-4 lg:gap-x-8">
          <div>
            <img src="https://tailwindui.com/img/ecommerce/icons/icon-delivery-light.svg" alt="" class="h-24 w-auto">
            <h3 class="mt-6 text-base font-medium text-gray-900">Free delivery to the US and canada</h3>
            <p class="mt-3 text-base text-gray-500">Because it would be dumb if we didn't</p>
          </div>
          <div>
            <img src="https://tailwindui.com/img/ecommerce/icons/icon-chat-light.svg" alt="" class="h-24 w-auto">
            <h3 class="mt-6 text-base font-medium text-gray-900">24/7 Customer Support</h3>
            <p class="mt-3 text-base text-gray-500">Reach out and we'll get back to you</p>
          </div>
          <div>
            <img src="https://tailwindui.com/img/ecommerce/icons/icon-fast-checkout-light.svg" alt="" class="h-24 w-auto">
            <h3 class="mt-6 text-base font-medium text-gray-900">Fast Shopping Cart</h3>
            <p class="mt-3 text-base text-gray-500">Look at the cart in that icon, there&#039;s never been a faster cart. What does this mean for the actual checkout experience? I don&#039;t know.</p>
          </div>
          <div>
            <img src="https://tailwindui.com/img/ecommerce/icons/icon-gift-card-light.svg" alt="" class="h-24 w-auto">
            <h3 class="mt-6 text-base font-medium text-gray-900">Gift Cards</h3>
            <p class="mt-3 text-base text-gray-500">We sell these hoping that you will buy them for your friends and they will never actually use it. Free money for us, it&#039;s great.</p>
          </div>
        </div>
      </section>
    </div>





</div>